### ISSUE TITLE
logic-proxy cannot connect to elasticsearch

### ISSUE THREAD

**Issue by fdrobnic** [FIWARE/production-on-k8s#5]
On microk8s, the following error is logged with the logic-proxy pod:

```
Elasticsearch ERROR: 2021-05-12T21:46:42Z
  Error: Request error, retrying
  HEAD http://elastic.docker:9200/ => getaddrinfo ENOTFOUND elastic.docker elastic.docker:9200
      at Log.error (/business-ecosystem-logic-proxy/node_modules/elasticsearch/src/lib/log.js:239:56)
      at checkRespForFailure (/business-ecosystem-logic-proxy/node_modules/elasticsearch/src/lib/transport.js:298:18)
      at HttpConnector.<anonymous> (/business-ecosystem-logic-proxy/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
      at ClientRequest.wrapper (/business-ecosystem-logic-proxy/node_modules/lodash/lodash.js:4929:19)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at emitErrorNT (internal/streams/destroy.js:66:8)

Elasticsearch WARNING: 2021-05-12T21:46:42Z
  Unable to revive connection: http://elastic.docker:9200/

Elasticsearch WARNING: 2021-05-12T21:46:42Z
  No living connections

2021-05-12 21:46:42.244  - INFO: TMF - Cannot connect to elasticSearch! (elastic.docker:9200)
{ Error: getaddrinfo ENOTFOUND apis.docker apis.docker:8080
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'apis.docker',
  host: 'apis.docker',
  port: '8080' }
Error:  { Error: getaddrinfo ENOTFOUND apis.docker apis.docker:8080
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'apis.docker',
  host: 'apis.docker',
  port: '8080' }
```

The logic-proxy pod is restarting indefinitely.

**Comment by dwendland** [comment]
This is not a problem with these instructions or the underlying Helm chart, but rather a problem with the logic proxy component itself. Could you file the issue here: https://github.com/FIWARE-TMForum/business-ecosystem-logic-proxy ?

As far as I know, this should be fixed in the next release. For the moment, could you try this image: fiware/biz-ecosystem-logic-proxy:v7.8.1rc1 ?

**Comment by fdrobnic** [comment]
All green with the v7.8.1rc1. :) May be useful if the BAE helm chart is updated to that version.

Obviously there is no need to file separate issue there, or is it?

**Comment by dwendland** [comment]
Although it's no official release, I've put this tag to the charts for the moment: https://github.com/FIWARE/helm-charts/pull/29
Needs to be updates as soon as we have the next release.
